theme: jekyll-theme-cayman

#Setup
title: [Natch support knowledge base]
description:
baseurl: ""
paginate:
values:
  layout:
  
# Contact
author:
  name: Natch support
  url: https://esc.be/support/
  baseurl: 
